# Generated by Django 4.0.2 on 2022-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributionteamsignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ZONE',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
