# Generated by Django 4.0.2 on 2022-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('s_type', models.CharField(max_length=255)),
                ('head_count', models.CharField(max_length=255)),
                ('receiever', models.CharField(max_length=255)),
                ('r_type', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
