# Generated by Django 4.0.2 on 2022-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_sub', models.CharField(max_length=255)),
                ('ngo_sub', models.CharField(max_length=255)),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('days', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.RenameField(
            model_name='request_manage',
            old_name='head_count',
            new_name='day_count',
        ),
    ]
