# Generated by Django 4.0.2 on 2022-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=256)),
                ('Ngo_name', models.CharField(max_length=256)),
                ('Profile_pic', models.ImageField(blank=True, null=True, upload_to='static/images/userspic')),
            ],
        ),
        migrations.CreateModel(
            name='Newteammember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=256)),
                ('User_email', models.CharField(max_length=256)),
                ('Ngo_email', models.CharField(max_length=256)),
            ],
        ),
    ]
