# Generated by Django 4.0.2 on 2022-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEAM_name', models.CharField(max_length=255)),
                ('member1', models.CharField(max_length=255)),
                ('member2', models.CharField(max_length=255)),
                ('member3', models.CharField(max_length=255)),
                ('member4', models.CharField(max_length=255)),
                ('member5', models.CharField(max_length=255)),
                ('hotel_image_upload', models.ImageField(blank=True, null=True, upload_to='static/images/TEAMPIC')),
            ],
        ),
    ]
