# Generated by Django 4.0.2 on 2022-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsignup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelsignup',
            old_name='hotel_Email',
            new_name='hotel_email',
        ),
        migrations.RenameField(
            model_name='hotelsignup',
            old_name='hotel_Phone',
            new_name='hotel_phone',
        ),
        migrations.AlterField(
            model_name='hotelsignup',
            name='auth_doc_upload',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/hotelsignupimages/AUTHENTICATION_DOCS'),
        ),
    ]
