# Generated by Django 4.0.2 on 2022-04-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ngosignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_name', models.CharField(max_length=255)),
                ('req_phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('req_email', models.EmailField(max_length=254)),
                ('passkey', models.CharField(max_length=255)),
                ('ZONE', models.CharField(max_length=255)),
                ('AREA', models.CharField(max_length=255)),
                ('CAPACITY', models.CharField(max_length=255)),
                ('image_upload', models.FileField(blank=True, null=True, upload_to='static/images/ngosignupimages')),
                ('author', models.BooleanField()),
            ],
        ),
    ]
