# Generated by Django 4.0.2 on 2022-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngosignup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngosignup',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/ngosignupimages'),
        ),
    ]
