# Generated by Django 4.0.2 on 2022-04-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngosignup', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USERS',
        ),
    ]
